CREATE TABLE IF NOT EXISTS EventLog
(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(40)
);

BEGIN;
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

INSERT INTO EventLog (NAME) VALUES('TEST_2');

COMMIT;