-- DISTINCT
DROP TABLE Users;
CREATE TABLE Users
(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(40)
);
INSERT INTO Users (Name) 
VALUES 
('HARRY'),
('HARRY'),
('HARRY'),
('GARRY'),
('MARRY'),
('JARRY'),
('ARNOLD'),
('PETER'),
('MARIA');

SELECT DISTINCT Name FROM Users;

-- ORDER BY
SELECT * FROM users ORDER BY name, id;
SELECT * FROM users ORDER BY name, id DESC;

-- LIMIT
SELECT * FROM Users LIMIT 2;

-- OFFSET
SELECT * FROM Users OFFSET 3;

-- OFFSET + LIMIT
SELECT Id FROM Users ORDER BY Id OFFSET 3 LIMIT 3;

-- IN
SELECT * FROM Users WHERE Name IN ('HARRY', 'ARNOLD');

-- BETWEEN
SELECT * FROM Users WHERE Id BETWEEN 1 AND 5;

-- LIKE
SELECT * FROM Users WHERE Name LIKE '%A%';

-- AVG
SELECT AVG(Id) FROM Users;

-- COUNT
SELECT COUNT(DISTINCT Name) FROM Users;
SELECT COUNT(Name) FROM Users;

-- SUM
SELECT SUM(Id) FROM Users;

-- MIN
SELECT MIN(Id) FROM Users; 

-- MAX
SELECT MAX(Id) FROM Users;

-- STRING_AGG
SELECT STRING_AGG(DISTINCT Name, ', ') AS ALL_NAMES FROM Users;

